# Generated by Django 3.2 on 2022-07-13 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('is_read', models.BooleanField(default=False, verbose_name='확인여부')),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name_plural': '푸시알림',
                'db_table': 'pushnotifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
